# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
    port: 8080

spring:
    # 环境 dev|prod
    profiles:
        active: dev
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss